import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { createContext } from 'react'
import useLocalStorage from '../../components/common/persistenciaUteis'
import styles from '/styles/Persistencia.module.css'

export const ThemeContext = createContext(null);

const Persistencia: NextPage = () => {
  const [theme, setTheme] = useLocalStorage('theme', 'light');
  const toggleTheme = () => {
    setTheme((curr: string) => (curr === "light" ? "dark" : "light"));
  };
  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      <div className={styles.container} id={theme}>
        <Head>
          <title>Persistencia</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
            <button onClick={() => setTheme('ligth')}> Ligth</button>
          </div>
          <div>
            <button onClick={() => setTheme('dark')}> dark</button>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </ThemeContext.Provider>
  )
}

export default Persistencia;
